# Model definition generated by Copilot from
# Frontend ts schema.
#
# Keep in-sync with
#
# web/app/components/workflow/nodes/if-else/types.ts#L55

from enum import StrEnum
from typing import Optional, Union

from pydantic import BaseModel, Field

from core.workflow.nodes.if_else.enum import ComparisonOperator


class LogicalOperator(StrEnum):
    """Logical operator enum."""

    AND = "and"
    OR = "or"


class VarType(StrEnum):
    """Variable type enum."""

    STRING = "string"
    NUMBER = "number"
    SECRET = "secret"
    OBJECT = "object"

    FILE = "file"

    ARRAY_STRING = "array[string]"
    ARRAY_NUMBER = "array[number]"
    ARRAY_OBJECT = "array[object]"
    ARRAY_FILE = "array[file]"

    # The following three members are different from `SegmentType`.
    # They are present in the frontend code, but not in the backend.
    #
    # Besides, `ARRAY_ANY` is present in backend code, but not found in
    # frontend code.
    ARRAY = "array"
    ANY = "any"
    BOOLEAN = "boolean"


class CaseItem(BaseModel):
    """Case item type."""

    case_id: str
    logical_operator: LogicalOperator
    conditions: list["Condition"]


class Condition(BaseModel):
    """Condition type."""

    id: str
    varType: VarType
    variable_selector: list[str] | None = None
    key: Optional[str] = Field(None, description="Sub variable key")
    comparison_operator: Optional[ComparisonOperator] = None
    value: Union[str, list[str]]
    numberVarType: Optional[str] = None  # This should match the VarType from tool/types.ts
    sub_variable_condition: Optional[CaseItem] = None


class Branch(BaseModel):
    """Branch type."""

    id: str


class NodeRunningStatus(StrEnum):
    """Node running status enum."""

    NOT_START = "not-start"
    WAITING = "waiting"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    EXCEPTION = "exception"
    RETRY = "retry"


class IfElseNodeType:
    """If-else node type."""

    logical_operator: Optional[LogicalOperator] = None
    conditions: Optional[list[Condition]] = None
    cases: list[CaseItem]
    isInIteration: bool
    isInLoop: bool


# Update forward references for nested types
Condition.update_forward_refs()
