"""add a counter table

Revision ID: 77155070034e
Revises: 4474872b0ee6
Create Date: 2025-06-19 13:47:00.083386

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77155070034e'
down_revision = '4474872b0ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counters',
        sa.Column('key', sa.String(length=70), nullable=False),
        sa.Column('value', sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint('key', name=op.f('counters_pkey'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counters')
    # ### end Alembic commands ###
